### ISSUE TITLE
Bug: Component inclusion results in "unexpected end of file" error

### ISSUE THREAD

**Issue by Swennet** [roots/acorn#182] opened 2022-02-04 16:19 UTC
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Introductory note
I have changed the structure of Bedrock and Sage to have certain folders living in the root of my project. I'm not sure if this causes the issue. I used the official acorn config file `config/view.php` to configure these paths.

The relevant folder structure is:

```
app/
└── View/
    └── Components/
        └── Button.php
resources/
└── views/
    └── components/
        └── button.blade.php
public/
└── content/
    └── cache/
        └── acorn/
            └── framework/
                └── views/
                    └── 4ca871573b12f73731765c6cb8ca42b1b55175ac.php
.env
composer.json        # → Combined Bedrock & Sage composer.json file
```

### What's wrong?
I have a custom component called "button" which I'm trying to include in my blade template. In my template I have the following blade component code:

```
/* Some HTML... */

<x-button>

/* Continued HTML... */
```

My component that lives in `resources/views/components/button.blade.php` only contains the following code:

```
<button>test</button>
```

Then in `app/View/Components/Button.php` I have the following:

```
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Button extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.button');
    }
}
```

In the generated .php file I can see the following code in place of the button component:

```
/* Some HTML... */

<?php if (isset($component)) { $__componentOriginal065ae5da12ba8e75c6b4e84d90798c2fb812b940 = $component; } ?>
<?php $component = $__env->getContainer()->make(App\View\Components\Button::class, []); ?>
<?php $component->withName('button'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php $component->withAttributes([]); ?>

/* Continued HTML... */
```

It looks like the second if statement `<?php if ($component->shouldRender()): ?>` doesn't close. The remaining content of the file does continue afterwards.

### Steps To Reproduce

1. Create a new component using `wp acorn make:component Button`
2. Include the component tag in a blade template file. `<x-button>`.
3. Check the page where the button should display.

### Expected Behavior

The component code should display properly without returning an error.

### Actual Behavior

The generated component code does not include a closure for the if statement that's generated.

### Relevant Log Output

```shell
Illuminate \ View \ ViewException (E_ERROR)
syntax error, unexpected end of file, expecting elseif (T_ELSEIF) or else (T_ELSE) or endif (T_ENDIF) (View: /home/vagrant/projects/example.com/resources/views/front-page.blade.php)
```

### Versions

v2.0.0-beta.8

**Comment by QWp6t** [comment] 2022-02-04 18:35
Hey @Swennet 👋🏻

I'm thinking this is a usage issue not a bug.

Given that this is what you have in your blade file:
```html
/* Some HTML... */

<x-button>

/* Continued HTML... */
```

I'm guessing you're experiencing this issue because you didn't close the component.

Your component can be self-closing, like this.
```xml
<x-button />
```


Or it can contain content inside of it, like this.
```xml
<x-button>Some content that gets passed as the `$slot` variable in button.blade.php</x-button>
```

See also: https://laravel.com/docs/8.x/blade#rendering-components


**Feel free to reopen this issue if this doesn't solve it.**

**Closed by QWp6t** 2022-02-04 18:35 UTC
Labels: bug
