### ISSUE TITLE
Livewire - No application encryption key has been specified.

### ISSUE THREAD

**Issue by natanael-aguiar** [roots/acorn#376] opened 2024-05-08 14:26 UTC
### Version

4.2.2

### What did you expect to happen?

Following this Livewire implementation tutorial: https://roots.io/acorn/docs/using-livewire-with-wordpress/
I hoped that by following this tutorial the livewire would be implemented successfully and without errors.

### What actually happens?

After following the implementation tutorial to the letter, this error "No application encryption key has been specified" occurs despite the fact that my .env file already has an APP_KEY defined.

![image](https://github.com/roots/acorn/assets/72773757/465508e2-8e9e-43c0-ac1a-ff549ae3a94b)

### Steps to reproduce

1. Start a new project with Bedrock and Sage.
2. Follow this Livewire implementation tutorial. (https://roots.io/acorn/docs/using-livewire-with-wordpress/)
3. After that, this error will appear as shown in the screenshot below.

![image](https://github.com/roots/acorn/assets/72773757/5b2e7328-4c18-4ec6-8748-32cce74e8208)

### System info

1. Windows 11;
2. WSL 2;
3. DDEV (Docker-based PHP development environments.);
4. Docker;

### Please confirm this isn't a support request.

Yes

**Comment by Log1x** [comment] 2024-05-08 14:48
Can you please make a support thread on Discourse.

**Comment by natanael-aguiar** [comment] 2024-05-08 19:39
@Log1x  Sorry, I did not get it! This seems like a bug to me, which channel should I report this to?

**Comment by Log1x** [comment] 2024-05-08 20:27
I see. It is due to https://github.com/roots/bedrock/pull/714

@QWp6t will have to follow up on how to approach this in Acorn.

**Comment by Log1x** [comment] 2024-05-08 20:52
We figured out the cause of this and a fix will be pushed shortly. 

Sorry about the confusion here– I was confident this stuff all worked back when I did it. The bug came from an unexpected place outside of Acorn. 😅

**Comment by Log1x** [comment] 2024-05-08 21:10
This has been fixed in https://github.com/roots/support/pull/4 and a released has been tagged.

Just run `composer update roots/support` in your Acorn project.

**Closed by Log1x** 2024-05-08 21:10 UTC
Labels: bug

**Comment by natanael-aguiar** [comment] 2024-05-09 13:54
@Log1x This step worked wonderfully, but another problem arose at the end of it all. I have an error in the console related to: /livewire/livewire.js returning a 404 status code

**Comment by Log1x** [comment] 2024-05-09 22:17
I tested everything on my fresh project I made to test this report and everything seems to work as intended. 😕

![Screenshot](https://i.imgur.com/lkyrlYl.png)

If you haven't figured it out still, feel free to make a post on Discourse and I can try to help.
